[build]
  command = "hugo --gc --minify && mkdir -p public/admin && cp -r static/admin/* public/admin"
  publish = "public"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  force = true

