[build]
command = "hugo --gc --minify && mkdir -p public/admin && cp -r static/admin/* public/admin"
publish = "public"

[[redirects]]
from = "/admin/*"
to = "/admin/index.html"
status = 200
force = true

# Add proper headers for YAML files
[[headers]]
for = "/admin/config.yml"
[headers.values]
Content-Type = "text/yaml; charset=utf-8"

[[headers]]
for = "*.yml"
[headers.values]
Content-Type = "text/yaml; charset=utf-8"

